"""Add Article table and Toutiao account fields

Revision ID: 3f7c352578ea
Revises: 451c9bdb73e1
Create Date: 2026-05-14 14:47:52.578600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f7c352578ea'
down_revision: Union[str, Sequence[str], None] = '451c9bdb73e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('articles',  # Table already exists
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('account_id', sa.Integer(), nullable=True),
    # sa.Column('title', sa.String(length=500), nullable=False),
    # sa.Column('content', sa.Text(), nullable=True),
    # sa.Column('category', sa.String(length=50), nullable=True),
    # sa.Column('tags', sa.JSON(), nullable=True),
    # sa.Column('cover_image_path', sa.String(length=500), nullable=True),
    # sa.Column('status', sa.String(length=20), nullable=True),
    # sa.Column('scheduled_publish_time', sa.DateTime(), nullable=True),
    # sa.Column('published_time', sa.DateTime(), nullable=True),
    # sa.Column('platform_article_id', sa.String(length=100), nullable=True),
    # sa.Column('views', sa.Integer(), nullable=True),
    # sa.Column('likes', sa.Integer(), nullable=True),
    # sa.Column('comments', sa.Integer(), nullable=True),
    # sa.Column('shares', sa.Integer(), nullable=True),
    # sa.Column('completion_rate', sa.Float(), nullable=True),
    # sa.Column('ab_test_id', sa.String(length=100), nullable=True),
    # sa.Column('variant_id', sa.String(length=50), nullable=True),
    # sa.Column('error_message', sa.Text(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_articles_account_id'), 'articles', ['account_id'], unique=False)
    # op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    # op.drop_index(op.f('email'), table_name='users')  # Table doesn't exist
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.drop_index(op.f('ix_users_id'), table_name='users')
    # op.drop_index(op.f('ix_users_username'), table_name='users')
    # op.drop_index(op.f('username'), table_name='users')
    # op.drop_table('users')
    # op.create_foreign_key(None, 'account_health_metrics', 'accounts', ['account_id'], ['id'])  # Already exists
    # op.add_column('accounts', sa.Column('qualification_for_bonus', sa.Boolean(), nullable=True))  # Already exists
    # op.add_column('accounts', sa.Column('toutiao_last_publish_time', sa.DateTime(), nullable=True))  # Already exists
    # op.add_column('accounts', sa.Column('toutiao_consecutive_days', sa.Integer(), nullable=True))  # Already exists
    # op.add_column('accounts', sa.Column('toutiao_qualification_for_bonus', sa.Boolean(), nullable=True))  # Already exists
    # op.create_index('idx_alert_created', 'alert_records', ['created_at'], unique=False)  # Already exists
    # op.create_index('idx_alert_type_status', 'alert_records', ['type', 'status'], unique=False)
    # op.create_index(op.f('ix_alert_records_created_at'), 'alert_records', ['created_at'], unique=False)
    # op.create_index(op.f('ix_alert_records_status'), 'alert_records', ['status'], unique=False)
    # op.create_index(op.f('ix_alert_records_type'), 'alert_records', ['type'], unique=False)
    # op.drop_index(op.f('idx_chapters_novel_id'), table_name='chapters')  # Skip: needed for foreign key
    # op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)  # Already exists
    # op.create_index(op.f('ix_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)  # Already exists
    op.alter_column('content_tasks', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='pending, processing, completed, failed, cancelled',
               existing_nullable=True)
    # op.drop_index(op.f('idx_fanqie_analytics_chapter_id'), table_name='fanqie_analytics')  # Already exists
    # op.drop_index(op.f('idx_fanqie_analytics_novel_id'), table_name='fanqie_analytics')
    # op.drop_index(op.f('idx_fanqie_analytics_stat_date'), table_name='fanqie_analytics')
    # op.create_index(op.f('ix_fanqie_analytics_chapter_id'), 'fanqie_analytics', ['chapter_id'], unique=False)
    # op.create_index(op.f('ix_fanqie_analytics_id'), 'fanqie_analytics', ['id'], unique=False)
    # op.create_index(op.f('ix_fanqie_analytics_novel_id'), 'fanqie_analytics', ['novel_id'], unique=False)
    # op.create_index(op.f('ix_fanqie_analytics_stat_date'), 'fanqie_analytics', ['stat_date'], unique=False)
    # op.drop_index(op.f('idx_novels_account_id'), table_name='novels')  # Already exists
    # op.create_index(op.f('ix_novels_account_id'), 'novels', ['account_id'], unique=False)  # Already exists
    # op.create_index(op.f('ix_novels_id'), 'novels', ['id'], unique=False)  # Already exists
    # op.create_foreign_key(None, 'nurturing_sessions', 'accounts', ['account_id'], ['id'])  # Already exists
    # op.create_index('idx_phone_platform', 'phone_records', ['phone_number', 'platform'], unique=False)
    # op.create_index('idx_phone_status', 'phone_records', ['status'], unique=False)
    # op.create_index(op.f('ix_phone_records_platform'), 'phone_records', ['platform'], unique=False)  # Already exists
    # op.create_index(op.f('ix_phone_records_released_at'), 'phone_records', ['released_at'], unique=False)
    # op.create_index(op.f('ix_phone_records_status'), 'phone_records', ['status'], unique=False)
    # op.create_index(op.f('ix_phone_records_used_at'), 'phone_records', ['used_at'], unique=False)
    # op.create_index('idx_account_content', 'publish_records', ['account_id', 'content_task_id'], unique=False)  # Already exists
    # op.create_index('idx_created_at', 'publish_records', ['created_at'], unique=False)
    # op.create_index('idx_publish_status_time', 'publish_records', ['publish_status', 'publish_time'], unique=False)
    # op.create_index(op.f('ix_publish_records_created_at'), 'publish_records', ['created_at'], unique=False)  # Already exists
    # op.create_index(op.f('ix_publish_records_publish_status'), 'publish_records', ['publish_status'], unique=False)
    # op.create_index(op.f('ix_publish_records_publish_time'), 'publish_records', ['publish_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publish_records_publish_time'), table_name='publish_records')
    op.drop_index(op.f('ix_publish_records_publish_status'), table_name='publish_records')
    op.drop_index(op.f('ix_publish_records_created_at'), table_name='publish_records')
    op.drop_index('idx_publish_status_time', table_name='publish_records')
    op.drop_index('idx_created_at', table_name='publish_records')
    op.drop_index('idx_account_content', table_name='publish_records')
    op.drop_index(op.f('ix_phone_records_used_at'), table_name='phone_records')
    op.drop_index(op.f('ix_phone_records_status'), table_name='phone_records')
    op.drop_index(op.f('ix_phone_records_released_at'), table_name='phone_records')
    op.drop_index(op.f('ix_phone_records_platform'), table_name='phone_records')
    op.drop_index('idx_phone_status', table_name='phone_records')
    op.drop_index('idx_phone_platform', table_name='phone_records')
    op.drop_constraint(None, 'nurturing_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_novels_id'), table_name='novels')
    op.drop_index(op.f('ix_novels_account_id'), table_name='novels')
    op.create_index(op.f('idx_novels_account_id'), 'novels', ['account_id'], unique=False)
    op.drop_index(op.f('ix_fanqie_analytics_stat_date'), table_name='fanqie_analytics')
    op.drop_index(op.f('ix_fanqie_analytics_novel_id'), table_name='fanqie_analytics')
    op.drop_index(op.f('ix_fanqie_analytics_id'), table_name='fanqie_analytics')
    op.drop_index(op.f('ix_fanqie_analytics_chapter_id'), table_name='fanqie_analytics')
    op.create_index(op.f('idx_fanqie_analytics_stat_date'), 'fanqie_analytics', ['stat_date'], unique=False)
    op.create_index(op.f('idx_fanqie_analytics_novel_id'), 'fanqie_analytics', ['novel_id'], unique=False)
    op.create_index(op.f('idx_fanqie_analytics_chapter_id'), 'fanqie_analytics', ['chapter_id'], unique=False)
    op.alter_column('content_tasks', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='pending, processing, completed, failed, cancelled',
               existing_nullable=True)
    op.drop_index(op.f('ix_chapters_novel_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.create_index(op.f('idx_chapters_novel_id'), 'chapters', ['novel_id'], unique=False)
    op.drop_index(op.f('ix_alert_records_type'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_status'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_created_at'), table_name='alert_records')
    op.drop_index('idx_alert_type_status', table_name='alert_records')
    op.drop_index('idx_alert_created', table_name='alert_records')
    op.drop_column('accounts', 'toutiao_qualification_for_bonus')
    op.drop_column('accounts', 'toutiao_consecutive_days')
    op.drop_column('accounts', 'toutiao_last_publish_time')
    op.drop_column('accounts', 'qualification_for_bonus')
    op.drop_constraint(None, 'account_health_metrics', type_='foreignkey')
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_account_id'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
